apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  #### Controllers
  #
  - role: controller
    ssh:
      address: 10.0.122.11
      user: core
      port: 22
  - role: controller
    ssh:
      address: 10.0.122.12
      user: core
      port: 22
  - role: controller
    ssh:
      address: 10.0.122.13
      user: core
      port: 22

  #### Workers
  #
  - role: worker
    ssh:
      address: 10.0.122.14
      user: core
      port: 22
  - role: worker
    ssh:
      address: 10.0.122.15
      user: core
      port: 22
  - role: worker
    ssh:
      address: 10.0.122.16
      user: core
      port: 22

  #### k0s configuration
  #
  k0s:
    version: v1.23.3+k0s.1 
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 10.0.122.10
          sans:
            - 10.0.122.10
        storage:
          type: etcd
        network:
          provider: calico
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
        installConfig:
          users:
            etcdUser: k0s-etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        telemetry:
          enabled: false
#        extensions:
#          helm:
#            repositories:
#            - name: haproxytech
#              url: https://haproxytech.github.io/helm-charts
#            charts:
#            - name: haproxy-ingress
#              chartname: haproxytech/kubernetes-ingress
#              version: "1.18.1"
#              namespace: ingress
#              values: |
#                controller:
#                  kind: Deployment
#                  ingressClassResource:
#                    name: haproxy
#                    default: true
#                service:
#                  type: LoadBalancer
