---
#cloud-config
# OS: Ubuntu 22.04
users:
- name: core
  groups: [ systemd-journal ]
  lock_passwd: True
  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
  shell: /bin/bash
  ssh_authorized_keys:
  - ssh-ed25519 <>
write_files:
- path: /etc/sysctl.d/99-k8s.conf
  content: |
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward = 1
    net.ipv4.conf.lxc*.rp_filter = 0
- path: /etc/modules-load.d/99-k8s.conf
  content: |
    br_netfilter
    overlay
runcmd:
- modprobe br_netfilter overlay
- sysctl --system
